// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywgiqlubqpictzqfseae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3Z2lxbHVicXBpY3R6cWZzZWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjAzMzQsImV4cCI6MjA3MDAzNjMzNH0.-yUCkJcRQOPckpseZN8zfvurzMiU9Wgr-rQS-qhw0-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});